/*
 * MIT License
 *
 * Copyright (c) 2017 Rishabh Kumar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package ui;

import crawler.Crawler;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.concurrent.Callable;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import link.Link;

/**
 *
 * @author in8RisKu
 */
public class ControlDesk extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ControlDesk
     */
    Future<Boolean> parsingExecutor = null;
    JPopupMenu popup = null;
    JMenuItem clearMenu, filterbyMenu;
    
    public ControlDesk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        filterTextField = new javax.swing.JTextField();
        ignoreTextField = new javax.swing.JTextField();
        crawlerButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable()
        {
            int statusCol = 1;
            public Component prepareRenderer(TableCellRenderer renderer, int row, int col) {
                Component comp = super.prepareRenderer(renderer, row, col);
                Object obj = (Object)getModel().getValueAt(row, statusCol);
                if(obj == null)
                {
                    return comp;
                }
                Integer value = (Integer)obj;
                if(value.intValue() > 200 && value.intValue() < 400)
                {
                    comp.setBackground(Color.YELLOW);
                    comp.setForeground(Color.BLACK);

                }
                else if(value.intValue() > 399)
                {
                    comp.setBackground(Color.RED);
                    comp.setForeground(Color.WHITE);
                }

                else
                {
                    if(row % 2 == 0)
                    {
                        comp.setBackground(Color.WHITE);
                        comp.setForeground(Color.BLACK);
                    }
                    else
                    {
                        comp.setBackground(new Color(240, 240, 240));
                        comp.setForeground(Color.BLACK);
                    }
                }
                return comp;//renderer.getTableCellRendererComponent(this, obj, false, false, row, col);
            }
        }
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Url");

        jLabel2.setText("Filter");

        jLabel3.setText("ignore");

        urlTextField.setText("https://github.com/");
        urlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextFieldActionPerformed(evt);
            }
        });

        filterTextField.setText("http");
        filterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTextFieldActionPerformed(evt);
            }
        });

        ignoreTextField.setText("https://github.com/about");
        ignoreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreTextFieldActionPerformed(evt);
            }
        });

        crawlerButton.setText("Crawl");
        crawlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlerButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ignoreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(urlTextField)
                    .addComponent(filterTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crawlerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crawlerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ignoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {
                "Serial", "Status Code", "Link", "Parent Link"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlTextFieldActionPerformed

    private void filterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTextFieldActionPerformed

    private void ignoreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ignoreTextFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        jTable1.setModel(new javax.swing.table.DefaultTableModel (
        new Object [][] {{}},new String [] { "Serial", "Status Code", "Link", "Parent Link"}));
        jTable1.updateUI();
        obj.clearReportData();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void crawlerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crawlerButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:       
        StringBuilder data = new StringBuilder();
        TableModel tm = jTable1.getModel();
        int rowcount = tm.getRowCount();
        int colcount = tm.getColumnCount();
        for(int j = 0; j < colcount; j++)
        {
            data.append(tm.getColumnName(j)).append(',');
        }
        data.append("\r\n");
        for(int i = 0; i < rowcount; i++)
        {
            for(int j = 0; j < colcount; j++)
            {
               data.append(tm.getValueAt(i, j)).append(',');
            }
            data.append("\r\n");
        }
        boolean flag = obj.writeToCSV(data.toString());
        if(flag)
        {
            JOptionPane.showMessageDialog(ControlDesk.this, "Report Saved!");
        }
        else
        {
            JOptionPane.showMessageDialog(ControlDesk.this, "Error Saving!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private Crawler obj;
    
    public ControlDesk(Crawler obj) 
    {
        this.obj = obj;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initComponents();    
                ControlDesk.this.setVisible(true);
                ControlDesk.this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                crawlerButton.addActionListener(ControlDesk.this);
                
                 popup = new JPopupMenu();
                filterbyMenu  = new JMenuItem("Filter by");
                filterbyMenu.addActionListener(new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {

                    }
                });
                popup.add(filterbyMenu);
                jTable1.setComponentPopupMenu(popup);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton crawlerButton;
    private javax.swing.JTextField filterTextField;
    private javax.swing.JTextField ignoreTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) 
    {
        if(ae.getActionCommand().equals("Crawl"))
        {
            obj = new Crawler(urlTextField.getText(), filterTextField.getText(), ignoreTextField.getText());
            crawlerButton.setText("Stop");
            obj.isCancelled = false;
            clearButton.setEnabled(false);
            saveButton.setEnabled(false);
            doParsing();
        }
        else
        {
            parsingExecutor.cancel(true);
            obj.isCancelled = true;
            crawlerButton.setText("Crawl");
            clearButton.setEnabled(true);
            saveButton.setEnabled(true);
        }
    }
    
    public void doParsing()
    {
        Callable updateUI = new Callable<Boolean>()
        {
            @Override
            public Boolean call() throws Exception 
            {
                obj.parse();
                JOptionPane.showMessageDialog(ControlDesk.this, "Crawling completed");
                crawlerButton.setText("Crawl");
                return true;
            }
        };
        
        parsingExecutor = Executors.newFixedThreadPool(1).submit(updateUI);
        new Thread()
        {
            public void run()
            {
                //boolean flag = true;
                while(!parsingExecutor.isDone() && !parsingExecutor.isCancelled())
                {
                    SwingUtilities.invokeLater(() -> {
                        ArrayList<Link> urlList =  obj.getUrlList();
                        
                        for(Link link:urlList)
                        {
                            DefaultTableModel dtm = ((DefaultTableModel )ControlDesk.this.jTable1.getModel());
                            int statusCode = link.getStatusCode();
                            int serial = dtm.getRowCount();
                            dtm.addRow(new Object[]{serial,statusCode,link.getLink(),link.getParentLink()});  //"ABC", jTable1.getRowCount()-1, 0);
 
                        }
                        //         logTextArea.append(s);
                        
                    //    ControlDesk.this.jTable1.updateUI();
                        //         ControlDesk.this.jScrollPane1.updateUI();
                        ControlDesk.this.jScrollPane2.updateUI();
                    });
                    try
                    {
                        Thread.sleep(800);
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            }
        }.start();
    }
    
    
    /*/
    private class CustomTableCellRender extends DefaultTableCellRenderer
    {
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col)
        {


            Component renderer = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
            String status = (String)value;
            if(status != null && status.length() > 0 && Integer.parseInt(status) > 199)
            {
                renderer.setBackground(Color.yellow);
                renderer.setBackground(Color.red);

            }
            else
            {
                renderer.setBackground(table.getBackground());
                renderer.setForeground(table.getForeground());
            }
            return renderer;
        }
    }
    /*/
    
}
